# Generated by Django 3.1.2 on 2020-11-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_target',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='max_Order_qty',
            field=models.CharField(default=5, max_length=2),
        ),
    ]
